BDOG-1370 Adds open pr rater
hmrc/health-indicators pull request #37
Opened 2021-04-19 14:51 UTC by JasperWagen

2021-04-20 12:40 UTC, chotai requested changes

2021-04-20 12:40 UTC, chotai commented on conf/app.routes
> +GET             /test/:repo            @uk.gov.hmrc.healthindicators.controllers.TestController.test(repo)
Has this been added accidentally?

2021-04-20 12:40 UTC, chotai commented on test/uk/gov/hmrc/healthindicators/raters/StalePRRaterSpec.scala
> +
some tests would be good

2021-04-20 12:40 UTC, chotai commented on app/uk/gov/hmrc/healthindicators/raters/StalePRRater.scala
> +class StalePRRater @Inject()(
Not a biggie, but `Pr` would be a bit more readable

2021-04-20 13:03 UTC, JasperWagen commented on conf/app.routes
> +GET             /test/:repo            @uk.gov.hmrc.healthindicators.controllers.TestController.test(repo)
Yep, good spot

2021-04-20 13:04 UTC, JasperWagen commented on test/uk/gov/hmrc/healthindicators/raters/StalePRRaterSpec.scala
> +
Turns out I pushed an old version, tests should be there now

2021-04-21 13:57 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +        logger.error(s"An error occurred when connecting to ${githubConfig.restUrl}repos/hmrc/$repo/pulls")
What is the API response for a non-existing repo? If it is 404, then it can't be treated as an error.

2021-04-21 14:08 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +        logger.error(s"An error occurred when connecting to ${githubConfig.restUrl}repos/hmrc/$repo/pulls")
So I believe we started using this pattern because if the error bubbles up it halts the scheduler and the rest of the info for the rest of the repos would not be updated. Is there a better way of doing this?

2021-04-21 14:14 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/controllers/TestController.scala
>  class TestController @Inject() (
Does this controller need to be version controlled??

2021-04-21 14:15 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/models/Indicators.scala
> +  override def toString: String = "prs-not-found"
These `toString` can be `vals`.

2021-04-21 14:22 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/controllers/TestController.scala
>  class TestController @Inject() (
Probably not!

2021-04-21 15:05 UTC, JasperWagen commented
test this please

2021-04-21 15:31 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +        logger.error(s"An error occurred when connecting to ${githubConfig.restUrl}repos/hmrc/$repo/pulls")
What if you get a 5xx or any other 4xx from Github? Will the scheduler halt in that case?

2021-04-21 15:32 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/raters/StalePRRater.scala
> +class StalePRRater @Inject()(
PRRRR 🐱

2021-04-21 15:44 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +      s"${githubConfig.restUrl}/repos/hmrc/$repo/pulls"
I think you need to pass `state` query param to specify that we want only open PRs

2021-04-21 15:52 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +                                 httpClient: HttpClient,
The formatting is disturbed here, I guess.

2021-04-21 15:57 UTC, anshulbajpai commented on test/uk/gov/hmrc/healthindicators/models/IndicatorsSpec.scala
> +      Json.toJson(ValidReadme: ResultType) mustBe JsString("valid-readme")
Does the compiler need some help here?

2021-04-21 15:58 UTC, anshulbajpai commented on .gitignore
> +app/uk/gov/hmrc/healthindicators/controllers/TestController.scala
I don't think this will delete the existing version of TestController.

2021-04-21 16:15 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/models/Indicators.scala
> +case object StalePR extends OpenPRResultType {
I think we are only interested in stale PRs and we will penalize for that. I don't think we will award services for no PRs or fresh PRs :)

Can we get rid of other types?

2021-04-22 08:26 UTC, JasperWagen commented on test/uk/gov/hmrc/healthindicators/models/IndicatorsSpec.scala
> +      Json.toJson(ValidReadme: ResultType) mustBe JsString("valid-readme")
Yeah couldn't find the type after play 28 upgrade

2021-04-22 09:01 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/models/Indicators.scala
> +case object StalePR extends OpenPRResultType {
I agree that this makes sense to negatively mark, however I could see us potentially moving to an only positive marking system, in which case having the distinction between types of pr info would be useful. WDYT?

2021-04-22 09:27 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/models/Indicators.scala
> +case object StalePR extends OpenPRResultType {
My point is the only important information is how many stale PRs they have? 
For negative marking, we deduct the points as you implemented here.
If we do positive marking, we'll treat No PRs and fresh PRs as a "good" and award them 100 points (for example) and deduct some points (like 5 points) for every stale PR they have.

2021-04-22 09:34 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +        logger.error(s"An error occurred when connecting to ${githubConfig.restUrl}repos/hmrc/$repo/pulls")
I presume so but unsure on how to test this

2021-04-22 09:34 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +                                 httpClient: HttpClient,
Ran scalafmt on the project

2021-04-22 09:41 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +      s"${githubConfig.restUrl}/repos/hmrc/$repo/pulls"
state is automatically set to open, I can change it to be explicit if that's more readable?

2021-04-22 10:12 UTC, anshulbajpai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +        logger.error(s"An error occurred when connecting to ${githubConfig.restUrl}repos/hmrc/$repo/pulls")
A failed Future from any of the rater [here](https://github.com/hmrc/health-indicators/blob/master/app/uk/gov/hmrc/healthindicators/services/HealthIndicatorService.scala#L54) will result in a failure and the scheduled task will be partially run and hence partial indicators will be persisted.

I think we need some logic here to ensure that we don't let the failures from raters bubble up.
Maybe create another ticket for this work.

2021-04-22 13:37 UTC, anshulbajpai approved these changes

2021-04-23 11:36 UTC, chotai requested changes

2021-04-23 11:36 UTC, chotai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
>      implicit val hc: HeaderCarrier = HeaderCarrier().withExtraHeaders(("Authorization", s"token $configKey"))
You don't need `withExtraHeaders` here

2021-04-23 11:36 UTC, chotai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
>      implicit val hc: HeaderCarrier = HeaderCarrier().withExtraHeaders(("Authorization", s"token $configKey"))
Or rather, this should be the same as `getOpenPRs`

2021-04-23 11:36 UTC, chotai commented on app/uk/gov/hmrc/healthindicators/raters/StalePrRater.scala
> +      case None          => Seq(Result(PRsNotFound, "PR information could not be found", None))
If there are no open PR's do we care? If there is no open PR then there can't be a stale PR right? It might be simpler to get rid of the option and just have a Seq[OpenPR]. 

Hint - Scala can convert between Options and Lists implicitly

2021-04-23 11:36 UTC, chotai commented on app/uk/gov/hmrc/healthindicators/connectors/GithubConnector.scala
> +  def getOpenPRs(repo: String): Future[Option[Seq[OpenPR]]] = {
Will this be simpler if we return `Future[Seq[OpenPR]]`. I've added a comment below.

2021-04-23 14:44 UTC, JasperWagen commented on app/uk/gov/hmrc/healthindicators/raters/StalePrRater.scala
> +      case None          => Seq(Result(PRsNotFound, "PR information could not be found", None))
Yeah I think we do, the distinction between not being able to find PR info (None) and no open PRs (Seq.empty) doesn't matter currently because we are negatively marking. However it gives us the flexibility to move to a positive marking system in the future without having to award points when no PR info is found.

2021-04-26 16:11 UTC, chotai approved these changes

2021-04-27 07:56 UTC, merged